### ISSUE TITLE
some more projects

### ISSUE THREAD

**Issue by eqv** [Microsvuln/Awesome-AFL#1]
Some more AFL related projects:
https://github.com/rohanpadhye/FuzzFactory
https://github.com/RUB-SysSec/grimoire
https://github.com/RUB-SysSec/kAFL

**Comment by ArashAll** [comment]
@eqv Cool! thanks, I will add them to the list soon!

Regards,

**Comment by Microsvuln** [comment]
Hi @eqv! thank you very much to mention these projects, I will add them to the list soon .

Thanks!

**Comment by vanhauser-thc** [comment]
also:
talos is not maintaining afl-dyninst anymore, my fork has dyninst10 support plus more features and speed: https://github.com/vanhauser-thc/afl-dyninst
Also afl+dynamorio: https://github.com/vanhauser-thc/afl-dynamorio

Then:
fairfuzz is really good: https://github.com/carolemieux/afl-rb
superion is a PITA to build and is per-format, but interesting otherwise: https://github.com/zhunki/Superion
untracer (very good speed, not so good coverage): https://github.com/FoRTE-Research/UnTracer-AFL
Angora: increased branch coverage by taint tracing without symbolic execution https://github.com/AngoraFuzzer/Angora
Neuzz: AFL with neural networks  https://github.com/Dongdongshe/neuzz  - never tried it though

**Comment by Microsvuln** [comment]
Hi @vanhauser-thc , thanks, your participation is greatly welcomed!

I've updated the list with the fuzzers you mentioned .

I've also already added fuzzers that were mentioned by @eqv .

Thanks!
